{
    "name": "ERP Platform Delivery Core",
    "summary": "Core data models for ERP implementation delivery",
    "version": "19.0.1.0.0",
    "category": "Services/Project",
    "depends": ["base", "project", "mail"],
    "data": [
        "data/erp_delivery_sequence.xml",
        "data/erp_delivery_cron.xml",
        "security/erp_security.xml",
        "security/ir.model.access.csv",
        "views/project_project_views.xml",
        "views/erp_solution_views.xml",
        "views/res_partner_views.xml",
        "views/project_task_views.xml",
        "views/project_milestone_views.xml",
    ],
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}